### ISSUE TITLE
Tinker´s construct

### ISSUE THREAD

**Issue by W125** [Scraft-Server/Scraft4#3]
Stencil table - ani tam nedam blank pattern a muzu vyndat pattern na malou nasadu a ani mi to neubere z inventare blank pattern.

**Comment by FilipK-CZ** [comment]
Vim. Opravene to je v nove verze ale nefunguje. Ale neda se to menit takze to neni nejhorsi

**Comment by W125** [comment]
a taky knapsack, kdyz zemru tak jeden vypadne vedle hrobu a jeden je v nem, zdvoji se.

**Comment by FilipK-CZ** [comment]
Obě chyby opraveny ve verzi 1.10. Děkuj za upozornění :)
