### ISSUE TITLE
Zacyklený ExtraUtils

### ISSUE THREAD

**Issue by ghost** [Scraft-Server/Scraft4#4]
Po načtení jakéhokoliv(Singl i Multiplayer)světa vyhodí tahle chyba:
Description: Unexpected error
java.lang.StackOverflowError: Unexpected error
    at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.getPipe(TNHelper.java:132)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:83)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
--asi 1000x to samé----

Znamená to, že se tam prostě provedl takový kód, který se pořád opakuje a Java ho tudíž vypne.
Doporučuji aktualizovat mód ExtraUtils.

**Comment by FilipK-CZ** [comment]
ExtraUtilities je dávno aktualizován a není to jeho chyba ale chyba rei's minimap

Edit: Opraveno ve verzi 1.9

**Comment by ghost** [comment]
Dobře, ale jak to může být chyba Minimapy, když je tam "com.rwtema.EXTRAUTILS.tileentity.transfernodes.TNHelper.getPipe(TNHelper.java:132)"

**Comment by FilipK-CZ** [comment]
Nevím 100% co tam mají špatně ale rei's minimapa neni oficialní. I na forech jine řešení není

**Comment by ghost** [comment]
ok

---------- Původní zpráva ----------

Od: gamecraft45 notifications@github.com

Komu: Scraft-Server/Scraft4 Scraft4@noreply.github.com

Datum: 28. 12. 2014 15:22:51

Předmět: Re: [Scraft4] Zacyklený ExtraUtils (#4)

"

Nevím 100% co tam mají špatně ale rei's minimapa neni oficialní. I na forech
jine řešení není

—

Reply to this email directly or view it on GitHub
(https://github.com/Scraft-Server/Scraft4/issues/4#issuecomment-68208396). 

"=
