### ISSUE TITLE
knapsack + gravestone, pripojeni k serveru

### ISSUE THREAD

**Issue by W125** [Scraft-Server/Scraft4#5]
Po smrti se zdvojuje knapsack, jeden vypadne vedle hrobu a druhy je v nem.

**Comment by W125** [comment]
Nacte se mi hra poprvi se nestihnu prihlasit, na podruhy to stihnu pak odejdu nebo me to kopne a uz se nemuzu pripojit, vzdy me to prihlasi na server a hned kopne a pise mi to : A fatal error has occured, this connection is terminated.

**Comment by FilipK-CZ** [comment]
Knapsack opraven. Na chybě A fatal error has occured, this connection is terminated se pracuje

**Comment by FilipK-CZ** [comment]
Chyba "A fatal error has occured, this connection is terminated" se zdá konečně opravená.
